name: teethseg
channels:
  - defaults
  - conda-forge
dependencies:
  - cmake=3.26.4
  - gcc_linux-64=13.2.0
  - python=3.11
  - pip=23.3.1
  - ipykernel=6.28.0
  - sortedcollections=2.1.0
  - numpy=1.24.3
  - scipy=1.12.0
  - scikit-learn=1.3.0
  - pip:
    - trimesh[easy]==4.3.1
    - triangle==20230923